apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: custom-amis
  region: us-east-1
  version: "1.22"

managedNodeGroups:
  - name: ng-ubuntu2004-1
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    privateNetworking: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
    launchTemplate:
      id: lt-0436ab6d653aec89e

  # - name: ng-centos7-1
  #   minSize: 1
  #   desiredCapacity: 1
  #   maxSize: 1
  #   privateNetworking: true
  #   iam:
  #     attachPolicyARNs:
  #       - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
  #       - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  #       - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
  #       - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
  #   launchTemplate:
  #     id: lt-0a883caf833b9c4db

  